---
name: Test deb repo
on:
  push:
  workflow_dispatch:

jobs:
  deb-test:
    name: Ensure Debian repository is usable
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: armv7l
            cpu: cortex-a7
            base_image: raspios_lite:latest
          - arch: armv7l
            cpu: cortex-a7
            base_image: raspios_lite:2021-05-07
    steps:
      - name: Wait for repo generation to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: main
          check-name: Generate Debian repository
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          commands: |
            # Wait for the deploy action, I can't figure out how to match on it
            # for lewagon/wait-on-check-action above.
            sleep 180

            curl -o /etc/apt/trusted.gpg.d/ai5a-asl.asc \
              https://raw.githubusercontent.com/AI5A/asl-pkgs/main/pkg_pub_key.asc

            echo "deb [signed-by=/etc/apt/trusted.gpg.d/ai5a-asl.asc] https://ai5a.github.io/asl-pkgs/deb/$(grep VERSION_CODENAME /etc/os-release | cut -d= -f2) $(grep VERSION_CODENAME /etc/os-release | cut -d= -f2) main" \
              > /etc/apt/sources.list.d/ai5a-asl.list

            apt-get update
            apt-get install -y asl-asterisk asl-update-node-list
